Parameters:
    EnviromentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    Stackname:
        Description: Stack name to be appended to nested security group stack
        Type: String

Resources:
    CloudWatchLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Join ['-',[!Ref Stackname,!Ref EnviromentName]]
            RetentionInDays: 7


Outputs:
    LogGroupName:
        Description: Cloudwatch log group
        Value: !Ref CloudWatchLogGroup